### ISSUE TITLE
Issue with the companion Mongey/kafka:0.3.0

### ISSUE THREAD

**Issue by paoloantinori** [pmuir/terraform-provider-rhoas#2]
Probably out of scope for this project but the examples fail on kafka provider with the following error on Fedora  34.
Setting an explicit `0.2.12` works just fine. 

```
18:00:22 (/tmp/terra)$ terraform plan
╷
│ Error: Plugin did not respond
│ 
│   with kafka_topic.prices,
│   on config.tf line 37, in resource "kafka_topic" "prices":
│   37: resource "kafka_topic" "prices" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-kafka_v0.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef5a7c]

goroutine 36 [running]:
github.com/Mongey/terraform-provider-kafka/kafka.NewClient(0xc0000e61b0, 0xc00043d7e0, 0x0, 0x42dd4a)
	/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/client.go:32 +0x1bc
github.com/Mongey/terraform-provider-kafka/kafka.(*LazyClient).init.func1()
	/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/lazy_client.go:23 +0x40
sync.(*Once).doSlow(0xc0002ef8c0, 0xc000599160)
	/opt/hostedtoolcache/go/1.13.15/x64/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.15/x64/src/sync/once.go:57
github.com/Mongey/terraform-provider-kafka/kafka.(*LazyClient).init(0xc0002ef8c0, 0xfc8f40, 0x1487958)
	/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/lazy_client.go:22 +0x3f8
github.com/Mongey/terraform-provider-kafka/kafka.(*LazyClient).CanAlterReplicationFactor(0xc0002ef8c0, 0x11d4f93, 0x12, 0x1)
	/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/lazy_client.go:101 +0x2f
github.com/Mongey/terraform-provider-kafka/kafka.customDiff(0xc000242b40, 0x114dfe0, 0xc0002ef8c0, 0xc000533560, 0xc000242b40)
	/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/resource_kafka_topic.go:305 +0xfe
github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Diff(0xc0004329c0, 0xc00023d450, 0xc000274a80, 0x1218000, 0x114dfe0, 0xc0002ef8c0, 0x14cc700, 0xc000229880, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/schema.go:509 +0xac2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).simpleDiff(0xc00044a080, 0xc00023d450, 0xc000274a80, 0x114dfe0, 0xc0002ef8c0, 0xc000274a01, 0xc00025d790, 0x40d34d)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:351 +0x85
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).SimpleDiff(0xc00044a180, 0xc00025d978, 0xc00023d450, 0xc000274a80, 0xc000276160, 0xc000274a80, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/provider.go:316 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PlanResourceChange(0xc000442068, 0x14cb860, 0xc000274450, 0xc00024ede0, 0xc000442068, 0xc000274450, 0xc0001faa80)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:633 +0x765
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x117fe00, 0xc000442068, 0x14cb860, 0xc000274450, 0xc00024ed80, 0x0, 0x14cb860, 0xc000274450, 0xc0002460c0, 0xb8)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3171 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00057c2c0, 0x14da560, 0xc000427500, 0xc00010e400, 0xc00009d2c0, 0x1ca6a68, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00057c2c0, 0x14da560, 0xc000427500, 0xc00010e400, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000498aa0, 0xc00057c2c0, 0x14da560, 0xc000427500, 0xc00010e400)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-kafka_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by pmuir** [comment]
This happened to me as well, it was caused by not setting a bootstrap server. Can you try outputting the bootstrap server as used by the kafka provider config and see if it's being retrieved properly?

**Comment by pmuir** [comment]
I'll try this in a container in a bit

**Comment by pmuir** [comment]
I reproduced with a clean run. This is being casued as the provider config is initialized before the resource is ready - I think the config is in the wrong place in this provider. I'll see if I can work around.

**Comment by pmuir** [comment]
Good find with the older version - pinning to that for now.
